#ifndef MENU_H
#define MENU_H

//메뉴의 종류
//26_21 MENU_SHOW_ALL MENU_SAVE_TEXT MENU_SAVE_HTML추가
//26_10 MENU_ADD_STUDENT_ENG추가
enum MENU { //ShowMenu()를 호출하는 함수라면 MENU열거체도 알아야한다.
	MENU_ADD_STUDENT, MENU_ADD_STUDENT_ENG, MENU_SHOW_ALL,
	MENU_SAVE_TEXT, MENU_SAVE_HTML, MENU_QUIT
};

MENU ShowMenu();

#endif